### ISSUE TITLE
Release v1.0.0?

### ISSUE THREAD

**Issue by rocheio** [kavu/go-resque#11]
Loving this package so far. I have a simple use case of a Go API that will queue jobs to a legacy service using PHP-Resque, and this has worked well for me over the past few days of testing. I found your solution to be a better fit to my use case than https://github.com/benmanns/goworker since I just need to enqueue jobs across a couple different redis servers.

Would you be willing to create a new release / git tag to capture the updates since the original release of [v0.1.0](https://github.com/kavu/go-resque/releases/tag/v0.1.0)? I'm using Go v1.11 and the default `go get` of this repo is pulling that old tag which does not include newest updates or match up with the README.

Workaround for this is to just do `go get github.com/kavu/go-resque@master`, which at time of writing will add to the go.mod file as `github.com/kavu/go-resque v0.1.1-0.20180606075045-ab0fac5095ec` and then everything works as expected.

**Comment by kavu** [comment]
Hey, @rocheio! I just pushed `v1.0.0` tag. I didn't add `go.mod` yet, I am not quite sure if I need to add to the root and subpackages. Anyway, can you try it now, will it work for you?

**Comment by rocheio** [comment]
That's perfect, thank you @kavu! With go mod it's just the consumer app that needs the mod / sum files, but it will use the git tags from any dependencies if available for versioning. And I guess the issue here that we just discovered is that it will default to the latest git tag, even if like this case the tag is way older than the most recent commit on master. Should be solved now for any new users that just do a default `go get github.com/kavu/go-resque`, they'll get that release you just tagged until you add a newer one.

Thanks again!

**Comment by kavu** [comment]
Great, thank you @rocheio! Glad to help!
